### ISSUE TITLE
Search between projects

### ISSUE THREAD

**Issue by Cycloone** [docat-org/docat#440]
Hi! I use unstable version of docat and try to search between documents in different projects. Unfortunaly docat find only last uploaded document in one project, but not find another. I tryed to reindex as describe in doc `curl -X POST http://localhost:8000/api/index/update` but this not help.

**Comment by reglim** [comment]
I think I know what your issue is. It's one of those I mentioned in #438.
We currently create a `tmp-index.json` file and create our index in there. In the end, we rename the `tmp-index.json` to `index.json` to reduce the time that anyone using search has incomplete results. However, this renaming does not work properly, and we don't really know why.

We have decided that we'll drop full-text search before releasing, so you'll still be able to find projects and versions, but without the problems we face with the current solution.

**Comment by reglim** [comment]
I'm going to close this as indexing isn't really an issue anymore, but if you continue to have problems with it, feel free to reopen it.
