### ISSUE TITLE
how can I stay in tag (like `latest`) in url without redirect to version in url

### ISSUE THREAD

**Issue by larrycai** [docat-org/docat#772]
I released doc in different version and always tag latest on latest version 

`0.2.1-2024.01.24` (`latest`), then I can use url `https://docat.example.com/#mydoc/latest/html/index.html` for sharing

# Problem

When I click links in that html page, the url will be changed to `https://docat.example.com/#mydoc/0.2.1-2024.01.24/html/gettingstarted.html` (version instead of `latest` tag)

It is annoying when I want to share the links inside

# Expected

I expect to keep the tag name inside url without changes

Can it be configured or need a patch for it

**Comment by reglim** [comment]
Hi @larrycai 

I'm not 100% sure if that's possible because it's been a while and the whole 
mechanism is pretty complicated. I thought that maybe we could achieve the same thing
by providing a share button in the bottom right corner to copy the link to the latest version
of the documentation.
Would that be a reasonable solution?

**Comment by larrycai** [comment]
yes, `ShareIt!` is a good idea! I like it!

**Comment by reglim** [comment]
@larrycai @randombenj What do you think of this?

![image](https://github.com/docat-org/docat/assets/79848181/936a7630-bf09-4f78-b49e-e45ebaa18a2f)

**Comment by larrycai** [comment]
nice, "hide version" looks fit better for my case ;-)

**Comment by larrycai** [comment]
expected a new release so I can use it, thanks

**Comment by reglim** [comment]
Will come as soon as #782 is merged as well :+1:
