### ISSUE TITLE
Uploaded pdf documents are not opened

### ISSUE THREAD

**Issue by alexanderbeck** [docat-org/docat#82]
Uploading a pdf document will not be shown directly. First, a page is shown that a pdf document exists.

> [
> { "name":"design-lib.pdf", "type":"file", "mtime":"Tue, 02 Feb 2021 16:45:06 GMT", "size":1139382 }
> ]

You have to add the document to the url yourself (`http://docs.company.com/#/project-lib/8.0.0/design-lib.pdf`), open that page and hit refresh because it is not opened the first time with that url.

**Comment by fliiiix** [comment]
I know this issue is old but the reason for this is nginx serves by default only things called `index`. Otherwise you need to use the full url. 

I am inclined to close this issue as `wontfix` because it is a limitation of nginx or basically every webserver.
What do you think @randombenj and @alexanderbeck ?

**Comment by alexanderbeck** [comment]
`wontfix`would be okay for me if that is the reason. But I would strongly recommend to document this on the help page. 
In addition, the first time I paste the full url, it does not show the pdf. I have to hit refresh button on the firefox browser.

Or is there a posibility to automatically redirect to the full url if a pdf is detected?

**Comment by fliiiix** [comment]
doesn't seem to be a big issue, and we print a warning now on upload
